name: publish

on:
  workflow_dispatch:
    # This workflow must be run from a Tag. A branch is not allowed.

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    # uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
      - uses: subosito/flutter-action@v2
      - name: Install dependencies
        run: dart pub get
      - name: Publish to pub.dev
        run: dart pub publish -f
